export enum Action {
    CALL = 'CALL',
    ADD_CONTACT = 'ADD_CONTACT',
    TOGGLE_CONTACT_WINDOW = 'TOGGLE_CONTACT_WINDOW',
    TOGGLE_ADD_CONTACT_WINDOW = 'TOGGLE_ADD_CONTACT_WINDOW'
}

export default Action;